# Generated by Django 3.0.6 on 2020-10-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='pulse',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
