# Generated by Django 3.0.6 on 2020-12-14 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201207_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='type',
        ),
        migrations.RemoveField(
            model_name='nutrientes',
            name='is_portion',
        ),
        migrations.RemoveField(
            model_name='nutrientes',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='nutrient',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Nutrientes'),
            preserve_default=False,
        ),
    ]
