# Generated by Django 3.0.6 on 2020-11-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201031_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='activity_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='lose_kcal',
            field=models.FloatField(default=0),
        ),
    ]
