# Generated by Django 3.0.6 on 2020-11-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201108_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='expected_carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='expected_fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='expected_kcal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='expected_protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='expected_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='expected_water',
            field=models.IntegerField(default=0),
        ),
    ]
