# Generated by Django 3.0.6 on 2020-11-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201114_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
