# Generated by Django 3.0.6 on 2020-12-14 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201214_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('portion', models.FloatField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Meal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
    ]
