# Generated by Django 3.0.6 on 2020-12-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201215_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.MealSet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='meals',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.MealSet'),
        ),
    ]
