# Generated by Django 3.0.6 on 2021-01-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201215_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
