# Generated by Django 3.0.6 on 2021-01-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210122_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='summary_carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='summary_fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='summary_kcal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='summary_protein',
            field=models.FloatField(default=0),
        ),
    ]
