# Generated by Django 3.0.6 on 2021-01-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210123_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='summary_portion',
            field=models.FloatField(default=0),
        ),
    ]
