  version: '3'
    
  services:
    web:
      build: ./web
      volumes:
          - ./web/:/usr/src/web/
      ports:
        - "5000:5000"
      depends_on:
        - api
      environment:
        FLASK_ENV: development
    api:
        build: ./api
        command: python manage.py runserver 0.0.0.0:5001
        volumes:
          - ./api/:/usr/src/api/
        ports:
          - "5001:5001"
        depends_on:
          - db
        env_file:
          - ./.env.dev
    db:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_DB=fitApp
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
  volumes:
    postgres_data: